[package]
name = "yew-app"
version = "0.1.0"
authors = ["Tran Viet Phuoc <phuoc.finn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"

[lib]
crate-type = ["cdylib", "rlib"]
